dataapp/urls.py
from django.urls import path
from . import views

app_name = 'dataapp'

urlpatterns = [
    path('', views.database_upload, name='database_upload'),
    # path('db/vis/', views.database_visual, name='database_visual'),

    path('crud/', views.UploadList.as_view(), name='upload_list'),
    path('crud/view/<int:pk>', views.UploadView.as_view(), name='upload_view'),
    path('crud/new', views.UploadCreate.as_view(), name='upload_new'),
    path('crud/edit/<int:pk>', views.UploadUpdate.as_view(), name='upload_edit'),
    path('crud/delete/<int:pk>', views.UploadDelete.as_view(), name='upload_delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dataapp.urls', namespace='dataapp')),
]

dataapp/models.py
from django.db import models


class Upload(models.Model):
    # All fields inside of the cars.csv file are manually put here for in the database
    car = models.CharField(max_length=60)
    mpg = models.DecimalField(max_digits=5, decimal_places=1)
    cyl = models.IntegerField()
    cyl_disp = models.DecimalField(max_digits=5, decimal_places=1)
    horsep = models.DecimalField(max_digits=5, decimal_places=1)
    weight = models.DecimalField(max_digits=6, decimal_places=1)
    accel = models.DecimalField(max_digits=4, decimal_places=1)
    model = models.IntegerField()
    # Only these three countries/regions are present in the .csv file
    COUNTRIES = (
        (0, 'US'),
        (1, 'Europe'),
        (2, 'Japan'),
    )
    origin = models.IntegerField(choices=COUNTRIES)

dataapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Upload


class UploadList(ListView):
    model = Upload


class UploadView(DetailView):
    model = Upload


class UploadCreate(CreateView):
    model = Upload
    fields = ['car', 'mpg', 'cyl', 'cyl_disp', 'horsep', 'weight', 'accel', 'model', 'origin']
    success_url = reverse_lazy('dataapp:upload_list')


class UploadUpdate(UpdateView):
    model = Upload
    fields = ['car', 'mpg', 'cyl', 'cyl_disp', 'horsep', 'weight', 'accel', 'model', 'origin']
    success_url = reverse_lazy('dataapp:upload_list')


class UploadDelete(DeleteView):
    model = Upload
    success_url = reverse_lazy('dataapp:upload_list')


def database_upload(request):
    # If we get a post request, send the HTML form
    if request.method == 'GET':
        return render(request, 'dataapp/database_upload.html', {})

    COUNTRIES = {'US': 0,
                 'Europe': 1,
                 'Japan': 2}

    # take item named FILES from request. Read and Decode said file (Decode because we don't want ASCII).
    csv_data = (request.FILES['csv_file']).read().decode("utf-8")
    lines = csv_data.split("\r\n")

    # new entries is a buffer for new upload objects
    # if I don't have this it will take ages for the .csv file to process everything
    new_entries = []
    # loop through all the rows in the csv
    for line in lines:
        # split row into column values
        fields = line.split(";")
        # .append will throw a new object in the buffer
        # Upload will create the new object with said parameters
        new_entries.append(Upload(
            car=str(fields[0]),
            mpg = float(fields[1]),
            cyl = int(fields[2]),
            cyl_disp = float(fields[3]),
            horsep = float(fields[4]),
            weight = float(fields[5]),
            accel = float(fields[6]),
            model = int(fields[7]),
            origin = COUNTRIES[fields[8]],
        ))
    # bulk_create is a django function that fill throw everything in the database all at once.
    Upload.objects.bulk_create(new_entries)
    # HttpResponse will let the user know everything went oke and that no error has occurred
    return HttpResponse('OK')


dataapp/templates/dataapp/database_upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>File Upload</title>
</head>
<body>
    <form action="{% url "dataapp:database_upload" %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="csv_file" required="True" >
        <input type="submit" >
    </form>
</body>
</html>

dataapp/templates/dataapp/database_visual.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

dataapp/templates/dataapp/upload_confirm_delete.html
<h1>Car Delete</h1>
<form method="post">{% csrf_token %}
    Are you sure you want to delete DIS CAR "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

dataapp/templates/dataapp/upload_detail.html
<h1>Car Details</h1>
<h2>Name: {{object.car}}</h2>
Mpg: {{ object.mpg }}<br>
Cylinder: {{ object.cyl }}<br>
Cylinder Displacement: {{ object.cyl_disp }}<br>
Horse Power: {{ object.horsep }}<br>
Weight: {{ object.weight }}<br>
Acceleration: {{ object.accel }}<br>
Mode: {{ object.model }}<br>
Origin: {{ object.origin }}<br>

dataapp/templates/dataapp/upload_form.html
<h1>Car Edit</h1>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

dataapp/templates/dataapp/upload_list.html
<!DOCTYPE html>
<h1>Cars</h1>

<table border="1">
<thead>
    <tr>
    <th>Name</th>
        <!--Car Details here-->
    <th>View</th>
    <th>Edit</th>
    <th>Delete</th>
    </tr>
</thead>
<tbody>
    {% for car in object_list %}
    <tr>
    <td>{{ car.car }}</td>
    <td><a href="{% url "dataapp:upload_view" car.id %}">view</a></td>
    <td><a href="{% url "dataapp:upload_edit" car.id %}">edit</a></td>
    <td><a href="{% url "dataapp:upload_delete" car.id %}">delete</a></td>
    </tr>
    {% endfor %}
</tbody>
</table>

<a href="{% url "dataapp:upload_new" %}">New</a>